### PR TITLE
Fix here for missing comma

### PR DESCRIPTION
**Pull request by mscbuck**
Addressing the error below when installing....

```
** R
Error in parse(outFile) : 
  /tmp/RtmpzZIjOM/R.INSTALLc14a7c3b05d4/fastadi/R/generative-model.R:9:5: unexpected symbol
8:     A = matrix()
9:     n
```

### CODE REVIEW

**Comment by alexpghayes** [comment]
Thanks. Can I ask what you're using `fastadi` for?

**Comment by mscbuck** [comment]
> Thanks. Can I ask what you're using `fastadi` for?

Mainly was addressing that I could not install `vsp` due to the `fastadi` requirement! But I work with recommendation systems in general, so always wanting to try out new methods / packages for fast embeddings.

**Comment by karlrohe** [comment]
Thanks Michael!

On Jun 15, 2021, at 10:45 AM, Michael Clutterbuck ***@***.******@***.***>> wrote:



Thanks. Can I ask what you're using fastadi for?

Mainly was addressing that I could not install vsp due to the fastadi requirement! But I work with recommendation systems in general, so always wanting to try out new methods / packages for fast embeddings.

**Comment by alexpghayes** [comment]
Thanks @mscbuck. I just dropped the dependency on `fastadi` and some other compiled code that should make `vsp` easier to use. Please let me know if you're stilling have installation structures. Also would love to know how you're using `vsp`!

**Pull request merged**
